// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ArrivalSidePreference
 *
 * Preference for which side of road to arrive on.
 */
export type ArrivalSidePreference = 'anySide' | 'curbSide';

/**
 * AvoidAreaRectangle
 *
 * Avoid area rectangle as GeoJSON Feature.
 *
 * bbox: [sw_lon, sw_lat, ne_lon, ne_lat]
 */
export type AvoidAreaRectangle = {
    /**
     * Type
     */
    type?: 'Feature';
    /**
     * Geometry
     */
    geometry?: {
        [key: string]: unknown;
    } | null;
    /**
     * Bbox
     *
     * [sw_lon, sw_lat, ne_lon, ne_lat]
     */
    bbox: [
        number,
        number,
        number,
        number
    ];
};

/**
 * AvoidAreas
 *
 * Avoid areas configuration.
 */
export type AvoidAreas = {
    /**
     * Rectangles
     *
     * Maximum 10 avoid area rectangles
     */
    rectangles?: Array<AvoidAreaRectangle>;
};

/**
 * AvoidType
 *
 * Road features to avoid.
 */
export type AvoidType = 'tollRoads' | 'motorways' | 'ferries' | 'unpavedRoads' | 'carpools' | 'alreadyUsedRoads' | 'borderCrossings' | 'tunnels' | 'carTrains';

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CalculateRouteRequest
 *
 * Calculate route request.
 *
 * Comprehensive request model supporting TomTom Calculate Route API v3 features.
 */
export type CalculateRouteRequest = {
    route_planning_locations: RoutePlanningLocations;
    /**
     * Suggested path as LineString
     */
    path?: GeoJSONLineString | null;
    /**
     * Legs
     *
     * Multi-leg route configuration
     */
    legs?: Array<RouteLeg> | null;
    /**
     * Avoids
     *
     * Road features to avoid (non-empty list)
     */
    avoids?: Array<AvoidType> | null;
    /**
     * Areas to avoid
     */
    avoid_areas?: AvoidAreas | null;
    /**
     * Route optimization strategy
     */
    route_type?: RouteType | null;
    /**
     * Traffic mode: live or historical
     */
    traffic?: TrafficMode | null;
    /**
     * Max Path Alternative Routes
     *
     * Maximum number of alternative routes (0-5)
     */
    max_path_alternative_routes?: number | null;
    /**
     * Travel mode: car or taxi
     */
    travel_mode?: TravelMode | null;
    /**
     * Preference for arrival side
     */
    arrival_side_preference?: ArrivalSidePreference | null;
    /**
     * Vehicle Heading In Degrees
     *
     * Vehicle heading in degrees (0-359)
     */
    vehicle_heading_in_degrees?: number | null;
    /**
     * Vehicle Max Speed In Kilometers Per Hour
     *
     * Maximum speed in km/h (0-250)
     */
    vehicle_max_speed_in_kilometers_per_hour?: number | null;
    /**
     * Vehicle Weight In Kilograms
     *
     * Vehicle weight in kilograms
     */
    vehicle_weight_in_kilograms?: number | null;
    /**
     * Vehicle engine type
     */
    vehicle_engine_type?: EngineType | null;
    /**
     * Electronic toll transponder status
     */
    vehicle_has_electronic_toll_collection_transponder?: ElectronicTollTransponder | null;
    /**
     * Departure Date Time
     *
     * Departure time (RFC3339 or 'now')
     */
    departure_date_time?: string | null;
    /**
     * Arrival Date Time
     *
     * Arrival time (RFC3339)
     */
    arrival_date_time?: string | null;
    /**
     * Attributes
     *
     * Route response attributes (TomTom header)
     */
    attributes?: string | null;
    /**
     * Attributes Exclude
     *
     * Excluded route attributes
     */
    attributes_exclude?: string | null;
    /**
     * Tracking Id
     *
     * Tracking ID for request correlation
     */
    tracking_id?: string | null;
    /**
     * Accept Language
     *
     * Accept-Language header value
     */
    accept_language?: string | null;
};

/**
 * CalculateRouteResponse
 *
 * Calculate route response.
 *
 * Contains one or more routes depending on maxPathAlternativeRoutes parameter.
 */
export type CalculateRouteResponse = {
    /**
     * Routes
     */
    routes: Array<Route>;
    /**
     * Formatversion
     */
    formatVersion?: string | null;
};

/**
 * DeviationPoint
 *
 * Deviation point information.
 */
export type DeviationPoint = {
    point: GeoJSONPoint;
    /**
     * Pathindex
     */
    pathIndex: number;
};

/**
 * ElectronicTollTransponder
 *
 * Electronic toll collection transponder type.
 */
export type ElectronicTollTransponder = 'all' | 'none';

/**
 * EngineType
 *
 * Vehicle engine type.
 */
export type EngineType = 'combustion' | 'electric';

/**
 * GeoJSONLineString
 *
 * GeoJSON LineString for path specification.
 *
 * Minimum 2 coordinates required.
 */
export type GeoJSONLineString = {
    /**
     * Type
     */
    type?: 'LineString';
    /**
     * Coordinates
     *
     * List of [longitude, latitude] coordinates
     */
    coordinates: Array<[
        number,
        number
    ]>;
};

/**
 * GeoJSONMultiPoint
 *
 * GeoJSON MultiPoint for waypoints.
 *
 * Maximum 150 waypoints supported.
 */
export type GeoJSONMultiPoint = {
    /**
     * Type
     */
    type?: 'MultiPoint';
    /**
     * Coordinates
     *
     * List of [longitude, latitude] coordinates
     */
    coordinates: Array<[
        number,
        number
    ]>;
};

/**
 * GeoJSONPoint
 *
 * GeoJSON Point with validated coordinates.
 *
 * Coordinates must be [longitude, latitude] in WGS84.
 * - longitude: -180 to 180
 * - latitude: -90 to 90
 */
export type GeoJSONPoint = {
    /**
     * Type
     */
    type?: 'Point';
    /**
     * Coordinates
     *
     * [longitude, latitude] in WGS84
     */
    coordinates: [
        number,
        number
    ];
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Leg
 *
 * Route leg (segment between waypoints).
 */
export type Leg = {
    summary: RouteSummary;
    path?: GeoJSONLineString | null;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProgressPoint
 *
 * Progress point along route.
 */
export type ProgressPoint = {
    /**
     * Pathindex
     *
     * Index in path coordinates
     */
    pathIndex: number;
    /**
     * Distanceinmeters
     */
    distanceInMeters: number;
    /**
     * Traveldurationinseconds
     */
    travelDurationInSeconds: number;
};

/**
 * Route
 *
 * Single calculated route.
 */
export type Route = {
    summary: RouteSummary;
    /**
     * Legs
     */
    legs?: Array<Leg> | null;
    /**
     * Sections
     */
    sections?: Array<Section> | null;
    /**
     * Guidance
     */
    guidance?: {
        [key: string]: unknown;
    } | null;
};

/**
 * RouteLeg
 *
 * Leg configuration for multi-leg routes.
 */
export type RouteLeg = {
    route_type?: RouteType | null;
    route_stop?: RouteStop | null;
    path?: GeoJSONLineString | null;
    /**
     * Avoids
     *
     * Avoid specific road types
     */
    avoids?: Array<AvoidType> | null;
};

/**
 * RoutePlanningLocations
 *
 * Route waypoints and stops.
 */
export type RoutePlanningLocations = {
    /**
     * Starting point
     */
    origin: GeoJSONPoint;
    /**
     * Destination point
     */
    destination: GeoJSONPoint;
    /**
     * Intermediate waypoints
     */
    waypoints?: GeoJSONMultiPoint | null;
};

/**
 * RouteStop
 *
 * Stop information for route legs.
 */
export type RouteStop = {
    /**
     * Pause Duration In Seconds
     *
     * Pause duration in seconds
     */
    pause_duration_in_seconds?: number | null;
    /**
     * Entry Points
     *
     * Possible entry points for this stop
     */
    entry_points?: Array<GeoJSONPoint> | null;
    /**
     * Preferred Entry Point Index
     *
     * Preferred entry point index (requires entry_points)
     */
    preferred_entry_point_index?: number | null;
};

/**
 * RouteSummary
 *
 * Route summary information.
 */
export type RouteSummary = {
    /**
     * Lengthinmeters
     */
    lengthInMeters: number;
    /**
     * Traveldurationinseconds
     */
    travelDurationInSeconds: number;
    /**
     * Trafficdelaydurationinseconds
     */
    trafficDelayDurationInSeconds?: number | null;
    /**
     * Trafficlengthinmeters
     */
    trafficLengthInMeters?: number | null;
    /**
     * Departuredatetime
     */
    departureDateTime?: string | null;
    /**
     * Arrivaldatetime
     */
    arrivalDateTime?: string | null;
    /**
     * Deviationdistanceinmeters
     */
    deviationDistanceInMeters?: number | null;
    /**
     * Deviationdurationinseconds
     */
    deviationDurationInSeconds?: number | null;
    deviationPoint?: DeviationPoint | null;
    /**
     * Progresspoints
     */
    progressPoints?: Array<ProgressPoint> | null;
};

/**
 * RouteType
 *
 * Route optimization type.
 */
export type RouteType = 'fast' | 'short' | 'efficient' | 'thrilling';

/**
 * Section
 *
 * Route section with various characteristics.
 */
export type Section = {
    /**
     * Startpathindex
     */
    startPathIndex: number;
    /**
     * Endpathindex
     */
    endPathIndex: number;
    /**
     * Sectiontype
     */
    sectionType?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TrafficMode
 *
 * Traffic mode for routing.
 */
export type TrafficMode = 'live' | 'historical';

/**
 * TravelMode
 *
 * Vehicle travel mode.
 */
export type TravelMode = 'car' | 'taxi';

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type routingCalculateRouteData = {
    body: CalculateRouteRequest;
    path?: never;
    query?: {
        /**
         * Force Refresh
         *
         * Force refresh from provider, skip cache
         */
        force_refresh?: boolean;
    };
    url: '/api/v1/routing/routes/calculate';
};

export type routingCalculateRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type routingCalculateRouteError = routingCalculateRouteErrors[keyof routingCalculateRouteErrors];

export type routingCalculateRouteResponses = {
    /**
     * Successful Response
     */
    200: CalculateRouteResponse;
};

export type routingCalculateRouteResponse = routingCalculateRouteResponses[keyof routingCalculateRouteResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
