"""Add medium_truck_accessible and large_truck_accessible to fuel_stations

Revision ID: 0253fbda0416
Revises: c3d4e5f6a7b8
Create Date: 2026-09-22 13:31:49.606859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0253fbda0416'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_stations', sa.Column('medium_truck_accessible', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('fuel_stations', sa.Column('large_truck_accessible', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_column('fuel_stations', 'truck_accessible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_stations', sa.Column('truck_accessible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('fuel_stations', 'large_truck_accessible')
    op.drop_column('fuel_stations', 'medium_truck_accessible')
    # ### end Alembic commands ###
